language: csharp
env:
  - MONO_THREADS_PER_CPU=50
os:
  - linux
before_install:
  - [ $TRAVIS_OS_NAME == "osx" ] || brew update
  - [ $TRAVIS_OS_NAME == "osx" ] || (brew list | grep icu4c || brew install icu4c)
  - [ $TRAVIS_OS_NAME != "osx" ] || sudo apt-get install libicu-dev libunwind8

script:
  - ./build.sh --quiet verify