language: csharp
sudo: false
env:
  - MONO_THREADS_PER_CPU=2000
os:
  - linux
  - osx
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - libicu-dev
    - libunwind8
before_install:
  - if [ $TRAVIS_OS_NAME == "osx" ] ; then brew update ; fi
  - if [ $TRAVIS_OS_NAME == "osx" ] ; then (brew list | grep icu4c || brew install icu4c) ; fi
script:
  - ./build.sh --quiet verify