language: csharp
env:
  - MONO_THREADS_PER_CPU=50
os:
  - linux
  - osx
addons:
apt:
  sources:
  - debian-sid
  packages:
  - libunwind8
before_install:
  - if [ $TRAVIS_OS_NAME == "osx" ] ; then brew update ; fi
  - if [ $TRAVIS_OS_NAME == "osx" ] ; then (brew list | grep icu4c || brew install icu4c) ; fi
  - if [ $TRAVIS_OS_NAME != "osx" ] ; then sudo apt-get install libicu-dev libunwind8 ; fi

script:
  - ./build.sh --quiet verify