sudo: required
env:
  - MONO_THREADS_PER_CPU=50
os:
  - linux
  - osx
services:
  - docker
before_install:
  - if [ $TRAVIS_OS_NAME != "osx" ] ; then docker pull glennc/dnx-build:latest ; fi
  - if [ $TRAVIS_OS_NAME == "osx" ] ; then brew update ; fi
  - if [ $TRAVIS_OS_NAME == "osx" ] ; then (brew list | grep icu4c || brew install icu4c) ; fi
script:
  - if [ $TRAVIS_OS_NAME != "osx" ] ; then docker run -v $TRAVIS_BUILD_DIR:/home/dev/code glennc/dnx-build /bin/sh -c "/home/dev/code/build.sh --quiet verify" ; fi
  - if [ $TRAVIS_OS_NAME == "osx" ] ; then ./build.sh --quiet verify ; fi