language: csharp
sudo: true
env:
  - MONO_THREADS_PER_CPU=50
os:
  - linux
  - osx
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - libunwind8
before_install:
  - [ $TRAVIS_OS_NAME == "osx" ] || brew update
  - [ $TRAVIS_OS_NAME == "osx" ] || (brew list | grep icu4c || brew install icu4c)
  - [ $TRAVIS_OS_NAME != "osx" ] || sudo apt-get install libicu-dev

script:
  - ./build.sh --quiet verify